-- liquibase formatted sql

-- changeset andrew:1
CREATE TABLE client_dog
(
    id            BIGINT PRIMARY KEY,
    name          TEXT           NOT NULL,
    chat_id       BIGINT        NOT NULL,
    phone_number  TEXT           NOT NULL,
    email         TEXT           NOT NULL,
    year_of_birth INTEGER        NOT NULL,
    dog_id        BIGINT UNIQUE NOT NULL,
    status        VARCHAR        NOT NULL
);

-- changeset andrew:2
CREATE TABLE dog
(
    id    BIGINT PRIMARY KEY,
    name  TEXT    NOT NULL,
    age   INTEGER NOT NULL,
    breed TEXT    NOT NULL,
    info  TEXT    NOT NULL,
    FOREIGN KEY (id) REFERENCES client_dog (dog_id)
);

-- changeset sergeyd:1
CREATE TABLE volunteer
(
    id            SERIAL PRIMARY KEY,
    name          TEXT           NOT NULL,
    user_id       BIGINT                 ,
    chat_id       BIGINT                 ,
    username      VARCHAR        NOT NULL,
    phone         TEXT
);

-- changeset sergeyd:2

CREATE TABLE report_dog
(
    id          BIGINT PRIMARY KEY NOT NULL,
    chat_id     BIGINT             NOT NULL,
    ration      varchar             NOT NULL,
    health      varchar             NOT NULL,
    habits      varchar             NOT NULL,
    info        VARCHAR             NOT NULL,
    client_dog_id   BIGINT REFERENCES client_dog(id),
    lastMessage date                NOT NULL,
    photo        bytea               NOT NULL,
    status       TEXT DEFAULT 'POSTED'
);

-- changeset andrew:3
CREATE TABLE client_cat
(
    id            BIGINT PRIMARY KEY,
    name          TEXT           NOT NULL,
    chat_id       BIGINT        NOT NULL,
    phone_number  TEXT           NOT NULL,
    email         TEXT           NOT NULL,
    year_of_birth INTEGER        NOT NULL,
    cat_id        BIGINT UNIQUE NOT NULL,
    status        VARCHAR        NOT NULL
);

-- changeset andrew:4
CREATE TABLE cat
(
    id    BIGINT PRIMARY KEY,
    name  TEXT    NOT NULL,
    age   INTEGER NOT NULL,
    breed TEXT    NOT NULL,
    info  TEXT    NOT NULL,
    FOREIGN KEY (id) REFERENCES client_cat (cat_id)
);

-- changeset sergeyd:3
CREATE TABLE report_cat
(
    id          BIGINT PRIMARY KEY NOT NULL,
    chat_id     BIGINT             NOT NULL,
    ration      varchar             NOT NULL,
    health      varchar             NOT NULL,
    habits      varchar             NOT NULL,
    info        VARCHAR             NOT NULL,
    client_cat_id   BIGINT REFERENCES client_cat(id),
    lastMessage date                NOT NULL,
    photo        bytea               NOT NULL,
    status       TEXT DEFAULT 'POSTED'
);

-- changeset sergeyd:4
CREATE TABLE users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    name    TEXT NOT NULL,
    is_dog  BOOLEAN NOT NULL
);