-- liquibase formatted sql


-- changeset andrew:1
CREATE TABLE dog
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT    NOT NULL,
    age   INTEGER NOT NULL,
    breed TEXT    NOT NULL,
    info  TEXT    NOT NULL
);


-- changeset andrew:2
CREATE TABLE client_dog
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT          NOT NULL,
    chat_id      BIGINT        NOT NULL,
    phone_number TEXT          NOT NULL,
    age          INTEGER,
    dog_id       BIGINT REFERENCES dog (id),
    status       VARCHAR
);

-- changeset sergeyd:1
CREATE TABLE volunteer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     TEXT    NOT NULL,
    chat_id  BIGINT,
    username VARCHAR NOT NULL,
    phone    TEXT
);

-- changeset sergeyd:2

CREATE TABLE report_dog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id       BIGINT  NOT NULL,
    ration        varchar NOT NULL,
    health        varchar NOT NULL,
    habits        varchar NOT NULL,
    info          VARCHAR NOT NULL,
    client_dog_id BIGINT REFERENCES client_dog (id),
    last_message  date    NOT NULL,
    photo         bytea   NOT NULL,
    status        TEXT DEFAULT 'POSTED'
);


-- changeset andrew:3
CREATE TABLE cat
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT    NOT NULL,
    age   INTEGER NOT NULL,
    breed TEXT    NOT NULL,
    info  TEXT    NOT NULL
);

-- changeset andrew:4
CREATE TABLE client_cat
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT          NOT NULL,
    chat_id      BIGINT        NOT NULL,
    phone_number TEXT          NOT NULL,
    age          INTEGER,
    cat_id       BIGINT REFERENCES cat(id),
    status       VARCHAR
);


-- changeset sergeyd:3
CREATE TABLE report_cat
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id       BIGINT  NOT NULL,
    ration        varchar NOT NULL,
    health        varchar NOT NULL,
    habits        varchar NOT NULL,
    info          VARCHAR NOT NULL,
    client_cat_id BIGINT REFERENCES client_cat (id),
    last_message  date    NOT NULL,
    photo         bytea   NOT NULL,
    status        TEXT DEFAULT 'POSTED'
);

-- changeset sergeyd:4
CREATE TABLE users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT  NOT NULL,
    name    TEXT    NOT NULL,
    is_dog  BOOLEAN NOT NULL
);

-- changeset sergeyd:5
ALTER TABLE report_cat DROP COLUMN health;
ALTER TABLE report_dog DROP COLUMN health;